services:
  db:
    image: postgres:15-alpine
    container_name: goal_master_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword123 # We will use env vars for the app, this is just for local dev
      POSTGRES_DB: goalmaster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
